### ISSUE TITLE
Watercooler results

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2144]
@brianlovin now that we've tried the watercooler in a couple communities, how did it work out? Do we want to make it a core part of Spectrum? What's the way to do that?

**Comment by ovflowd** [comment]
Sorry for invading this discussion, but most of the times why I become "mad" with the water cooler ones, it's because the loading time, or when I add a new message it scroll's all over to the last messages, instead of just continuing in the point I was.

Another community app called Band (band.us) It has a very good way of "built-in" water cooler, all the chat threads actually dig them very well.

Also the loading of the messages when you click to load more aren't the best ones. Images most of the times spend a time loading, so lazy-loading them could be very useful. Also having a layer saying how many messages I missed since my last view, and clicking it to rolling/scrolling in to the state of my last view, like WhatsApp, Band.us and Discord and Slack does, it could be very useful.

**Comment by brianlovin** [comment]
We are continuing forward with improvements to the watercooler itself and to the presentation/prominence of watercoolers on community views. Move forward!
