### ISSUE TITLE
Athena scaling breaks message notification batching

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#2471]

**Comment by mxstbr** [comment]
Gotta fix this though so we don't have to scale athena to 1. We had 10k backlogged jobs today due to all the traffic...

**Comment by mxstbr** [comment]
#2710 does some cleanup work to make sure individual instances of athena scale better by themselves and don't run out of mem eventually. (I think that's why we ended up with 10k backlogged jobs and none being processed)

Now the last bit here is to make sure that we can run multiple instances of athena concurrently. WIP thoughts coming up below.

**Comment by mxstbr** [comment]
Right now, athena buffers new notifications in memory for a certain amount of time and batches them into a single email to avoid overwhelming inactive users with 10 emails only because a person replied 10 different times in quick succession. 

Instead of buffering them in memory, we should buffer them in Redis with bull:

1. We add a new job to send a notification email, delayed by X amount and keyed by some unique key to that person (`Queue.add(, { delay: X, jobId: userId + whatever })`)
  2.1. Delay runs out without a new notification coming in, hermes processes the job and sends the email
  2.2. Before the delay runs out, a new notification comes in for the same user. We check whether we have a job for them (`Queue.getJob(userId + whatever)`)
    3.1. We don't have an existing job for them, go to step 1.
    3.2. We have an existing job, we merge that data into the new data (we already have that logic), then add that as the same job with the same delay and id, overwriting the old one

Theoretically, at least in my mind, this should work as it does today. We'll see if it actually works out that way!
