### ISSUE TITLE
Prevent zip file uploads

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#2494]
https://alpha.spectrum.chat/notifications?thread=f2af9b43-4141-46e6-b46d-60d04d63d6d4

**Comment by yuanchenxi95** [comment]
The bug seems to not exist anymore. In the alpha branch build, I am not able to upload a zip file anymore. 

Branch: alpha
File name: mediaUploader.js
Line: 104
The MediaInput Component checks the type of the file. 
          <MediaInput
            type="file"
            accept={'.png, .jpg, .jpeg, .gif, .mp4'}
            multiple={false}
            onChange={this.onChange}
          />

https://github.com/withspectrum/spectrum/blob/alpha/src/components/chatInput/components/mediaUploader.js

**Comment by brianlovin** [comment]
Thanks for the catch @yuanchenxi95 - would you be open for adding those checks on the backend? We should also have some size checks as well to ensure people aren't bypassing client restrictions and sending up massive files.

**Comment by yuanchenxi95** [comment]
Sure. What size should it be? I think the media also includes mp4 files.

**Comment by mxstbr** [comment]
I think the limit should be 25MB

**Comment by brianlovin** [comment]
We use roughly 3mb and 25mb as free/pro limits:
```js
export const FREE_USER_MAX_IMAGE_SIZE_BYTES = 3000000;
export const PRO_USER_MAX_IMAGE_SIZE_BYTES = 25000000;
```

So 25mb cap sounds perfect.

**Comment by yuanchenxi95** [comment]
For the file size restriction, the server uses [apollo-upload-server](https://github.com/jaydenseric/apollo-upload-server) library. It set the file upload limit to 50MB at middleware/index.js. Do you want this to be changed to 25MB?

Branch: alpha
File name: [api/middleware/index.js](https://github.com/withspectrum/spectrum/blob/alpha/api/routes/middlewares/index.js)
Line: 40 to 44.

**Comment by mxstbr** [comment]
Oh yeah that should be 25MB, and then we should restrict the file type to only be images, right?

**Comment by yuanchenxi95** [comment]
Should  the type of file being uploaded be restricted at the apollo-upload-server level, or should it be restricted at the uploadImage() method level?

**Comment by mxstbr** [comment]
Probably at the apollo-server-upload level if possible?

**Comment by yuanchenxi95** [comment]
I did some research about the apollo-server-upload library. It seems that it does not support the file type validation feature yet. There is an issue opened for mimetype validation: [How reject uploading after checking mimetype](https://github.com/jaydenseric/apollo-upload-server/issues/64).

I have implemented the uploadImage() method to validate the mimetype. 
```javascript 
export const uploadImage = async (
  file: FileUpload,
  entity: EntityTypes,
  id: string
): Promise<string> => {
  const validMediaTypes = ['image/gif', 'image/jpeg', 'image/png', 'video/mp4'];
  let { mimetype } = await file;
  // mimetype not in the validMediaType collection
  if (_.indexOf(validMediaTypes, _.toLower(mimetype)) < 0) {
    return new Error(`Unsupported media type ${mimetype}`);
  }

  return await upload(file, entity, id).catch(err => {
    throw new Error(err);
  });
};

```

The problem is that how to convert the Error to UserError, and how to return it to the frontend. I am thinking to catch the error and convert it.
```javascript
    let url;
    try {
      url = await uploadImage(file, 'threads', message.threadId);
    } catch (err) {
      return new UserError(err.message);
    }
```
This solution will require to change every uploadImage() call on the backend.

**Comment by mxstbr** [comment]
That seems fine to me—how many of those do we have?

**Comment by yuanchenxi95** [comment]
The method uploadImage is called in:
addMessage.js
community.js
createDirectMessageThread.js
editThread.js
publishThread.js
user.js
