### ISSUE TITLE
Channel icons get mixed up in the sidebar

### ISSUE THREAD

**Issue by mangej** [withspectrum/spectrum#2711]
I'm running macOS and safari. Sometimes the icons in the channel list get mixed up as you can see in the image below:  

![sidebar](https://user-images.githubusercontent.com/15796457/38314675-13b04576-3827-11e8-9ef9-23e672bb8a7e.png)

**Comment by brianlovin** [comment]
We've had a few reports of this in the past, but no consistent way to repro; do you know if there was anything in particular you were doing before this happened? Or did they load in like this?

**Comment by mangej** [comment]
I've been doing some testing: 

Here is a gif where I press on refresh button in safari. You can see at first the channels got their right icons during the initial loading but after they are loading the order of the channels are changed but the icons are not following. 

![spectrum-channels](https://user-images.githubusercontent.com/15796457/38317038-6cc7d39a-382c-11e8-853c-b90b6025f7e9.gif)

I also noticed if I go to another page (e.g. Explore) and then go back to Home the channels will have the correct icon but after a page refresh in safari the icons will be mixed up again. 

Maybe it's something with my cache?

**Comment by brianlovin** [comment]
I'm wondering if it's something in our `Avatar` component - we do some tricky state management there to handle fallback images. In `src/components/avatar/image.js` there might be something going on where it retains the old src even though the list is updating.

That sidebar list *does* get ordered by your rep in each community, which is why I think the list updates in the first place - although it should really only render with the proper order at all.

**Comment by brianlovin** [comment]
Ah, so I see - we are sorting the sidebar list by reputation in the community, but if the rep is 0 it looks like the rest of the list will just be random. Perhaps we need a fallback there for reputation then alphabetical? So that the order will always be the same, and might circumvent the images mismatch problem.

**Comment by mxstbr** [comment]
Yeah that sounds like an issue with `src/components/avatar/image.js`—we probably never check whether the passed `src` changes, only ever rendering the first initially loaded image.

**Comment by brianlovin** [comment]
Yeah. So there are two fixes needed here:

1. Add alphabetical sorting as a fallback to community lists to handle 0 reputation communities
2. Re-render image components if the `src` prop changes
