### ISSUE TITLE
Open thread in new tab does not work with search results

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#2753]
Discussion: https://spectrum.chat/thread/5801f8ca-166f-434b-be23-93625c6eb8c4

**Comment by kapillamba4** [comment]
@brianlovin, The actual problem seems to be only in production build of spectrum, i tried development build but cannot reproduce this bug.

Also i cannot npm start build-api for production build, getting this error:
```
Creating a pool connected to undefined:undefined
Unhandled rejection RangeError [ERR_SOCKET_BAD_PORT]: Port should be > 0 and < 65536. Received undefined.
```
I think i need to deploy production on aws using now.sh, i don't have aws account. Is there any way i can run try to fix this bug without an aws account?

**Comment by brianlovin** [comment]
I'm unable to repro this anymore, but I think the problem here is related to other people that visit `?t=:id` urls and it ignores the query param, redirecting immediately to the top item in the feed.
