### ISSUE TITLE
How to scale changefeeds for more sane side effect management

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#3031]
Up until now we've been stuck in the following situation:
Certain worker servers use changefeeds to process changes in the db and dispatch jobs to handle downstream side effects. E.g a user is deleted, vulcan receives a changefeed alert and removes the user from search indexing.

Until now we've been unhappy with this solution because we feel trapped by the inability to vertically scale instances of a worker (e.g. 3 instances of vulcan would run the job 3 times). This would obviously be very very bad for a worker like Pluto, which processes payment events.

However, I found this bit in the rethink docs:

> Changefeeds perform well as they scale, although they create extra intracluster messages in proportion to the number of servers with open feed connections on each write. This can be mitigated by running a RethinkDB proxy server (the rethinkdb proxy startup option); read Running a proxy node for details.

I found some docs here: https://github.com/rethinkdb/docs/issues/962#issuecomment-194006164

> When should I use a RethinkDB proxy?
> Primary use cases include:
> Scaling changefeeds.

> A proxy will manage changefeeds locally, and reduce the overhead (RAM, CPU and network)
on the database servers. For any write operation to a table with active changefeeds,
a database server only sends a single network message to a given proxy. If for example
10,000 clients are listening through a proxy to changes on a particular table, the
database server(s) hosting the table will send a single network message to the proxy when
the table is changed. The proxy then takes care of forwarding the change message to all
10,000 clients locally.

Unfortunately, the docs here are pretty bad at knowing how to enable a proxy connection in the config file (they only document the `--proxy` flag in the cli. I also didn't see any proxy documentation in the `rethinkdb-dash` docs. And I'm not sure exactly how this setup changes the fact that we already run a proxy on EC2.) 

But, just want to float this idea @mxstbr: assuming we could figure out a proper proxy config, couldn't we architect our backend in the following way:

1. Create a single changefeed hub that can vertically scale instances
2. This single changefeed hub gives us one place where we can easily see what the side effects are of a database change. Right now this is getting pretty spaghetti-like in our backend because we have several workers with changefeeds on the same table that do different things.
3. Possibly this changefeed hub should live on the api server; not sure about this, but my thinking is that if the changefeeds crash it should at least crash in sync with the api so that we don't get out of sync :P

Here's an example of how the output might look:

```js
export const newCommunity = () =>
  listenToNewDocumentsIn(db, 'communities', data => {
    // each of these are bull queues 
    indexCommunityInSearchQueue.add(data)
    sendNewCommunityWelcomeEmailQueue.add(data)
    sendAdminNewCommunityCreatedWelcomeEmailQueue.add(data)
    createStripeCustomerQueue.add(data)
    // ... etc
  });
```

Personally this seems more sane than our current setup which is:
1. API side effects in `api/models/community` which dispatches a couple queue jobs from the `createCommunity` function
2. Changefeed on Pluto to create a stripe customer
3. Changefeed on Vulcan to index in search

WDYT?

**Comment by mxstbr** [comment]
You are confusing a couple things here, let me clear this up:

**What those docs are referring to is deduplicating the communication between the different nodes in RethinkDB, not your application-side changefeeds**—even with the proxy if you connect two changefeeds for the same thing both will get pinged with new data, as it should be. In fact, we already run a proxy (and three nodes) in AWS otherwise we wouldn't be able to handle the traffic we have!

On top of that, changefeeds still scale very poorly even with a proxy in front of the nodes, which is the problem we ran into when we got all those "Connection dropped" errors all the time.

----

There is still a way to make this work, and make it work when we scale, with the same trick I used for the notification batch processing, turning the incoming changefeed data into unique jobs with `bull`:


1. We have a database listener in each instance like we do now
2. When new data comes in that database listener adds a job to a queue with its `jobId` set to something unique to that record (e.g. the payments records ID)
3. Even though all instances add that job, only a single one is retained as they have the same `jobId`!
4. The same worker  also listens to new jobs in that queue, and processes them. Because it's now only a single job in the queue, only a single instance will process the job. Scalability! :tada: 

That's what I did with the notification batch processing, and it's been working relatively well. We could do the same thing for Pluto and Vulcan too.

**Comment by johnnynotsolucky** [comment]
> This single changefeed hub gives us one place where we can easily see what the side effects are of a database change. Right now this is getting pretty spaghetti-like in our backend because we have several workers with changefeeds on the same table that do different things.

I agree that it is a mission to find all the side-effects from a mutation, however I feel that moving them all into a single centre might make it harder later on to maintain; In your example, you're now dependant on four separate things. If you wanted to turn off Algolia, you'd have to remove all those queues from the hub, whereas currently, you can simply switch off Vulcan.

Dev experience might suffer too. For example, it means if there's a listener that adds to some Stripe queue, I'd probably need to have Stripe testing details so that the hub can run. Right now we just don't run the Stripe worker 😅  

> but my thinking is that if the changefeeds crash it should at least crash in sync with the api so that we don't get out of sync :P

The RethinkDB `change` command has a `changefeedQueueSize` argument which defaults to 100,000 per changefeed. If the Spectrum changefeeds crashed, once restarted they should be able to continue processing and catch up quite easily.

That said, you probably don't need to be too concerned about the API falling out of sync with the changefeeds. As long as the changefeeds start processing before Rethink starts dropping messages, you should be 👍And if your Rethink cluster goes down you won't have any messages in the queue anyway.

https://rethinkdb.com/api/javascript/changes/

> API side effects in api/models/community which dispatches a couple queue jobs from the createCommunity function

https://github.com/withspectrum/spectrum/issues/2383 covers that :-D

**Comment by brianlovin** [comment]
> You are confusing a couple things here, let me clear this up:

Thanks for the explanation, really appreciate it. I can see how I was confusing things.

> That's what I did with the notification batch processing, and it's been working relatively well. We could do the same thing for Pluto and Vulcan too.

Makes sense!

> I agree that it is a mission to find all the side-effects from a mutation, however I feel that moving them all into a single centre might make it harder later on to maintain; In your example, you're now dependant on four separate things. If you wanted to turn off Algolia, you'd have to remove all those queues from the hub, whereas currently, you can simply switch off Vulcan.

Yeah, I can see both sides of the coin here. Having a single hub of changefeeds from which to understand the side effects of changes in the db sounds attractive. But I understand how that also changes the way we build versus just having a single worker do its thing that we can turn on/off and scale independently. 

Thanks for the thoughts on this guys. I'll refer to this issue going forward as I do more changefeed work, but will close for now :)

**Comment by johnnynotsolucky** [comment]
In the interim, it should be possible to have some sort of auto-generated documentation to create a central repository of mutation side-effects. Using something like [babylon](https://github.com/babel/babel/tree/master/packages/babylon) it's trivial to parse the AST and figure out which mutations are triggering listeners in worker changefeeds.

You have the benefit of having all your source in a monorepo which means we can glob the entire thing and generate a single doc with all mutations neatly grouped.

This should make it easier to figure out what the potential side-effects are for your mutations and also keeps services nicely separated.

@brianlovin I might be really over-thinking this issue 😄

**Comment by mxstbr** [comment]
@johnnynotsolucky ohh that would be really rad!

**Comment by mxstbr** [comment]
Totally overengineered though :sweat_smile:

**Comment by johnnynotsolucky** [comment]
> Totally overengineered though 😅

That's what bothers me 😣

If y'all think it would be useful, a naive POC would scan the repo for all calls to the listen functions in changefeed-utils, `listenToChangedFieldIn`, `listenToNewDocumentsIn`, etc and generate a doc based on that. You can get an idea from that of the work involved, and whether its even a feasible solution?

**Comment by mxstbr** [comment]
It's honestly probably not worth it at the moment 😅

**Comment by johnnynotsolucky** [comment]
Haha, I didn't think so :-D
