### ISSUE TITLE
Give leaving a community slightly more friction - especially for team members

### ISSUE THREAD

**Issue by superbryntendo** [withspectrum/spectrum#3250]
Clicking the Member button on a community shouldn't leave it without a modal confirming the decision - especially if you're a team member since a. the button is unclear in its function at first glance, and b. it adds complexity at several levels when re-joining.

**Comment by gokaygurcan** [comment]
Hi,

I also have the same feeling, but instead of showing a popup, I was thinking to differentiate normal state and hover state of the buttons. In hover state, for example, the button might become red with a different icon (`door-leave`) and different text (`Leave`) to visualize the action. 

Popup is kind of annoying and overkill imho. With a proper visualization, there won't be huge amount of people who clicks the button by mistake. 

I hope this makes sense. And thanks in advance!

**Comment by brianlovin** [comment]
We did this!
