### ISSUE TITLE
Deploying on AWS instead of NOW

### ISSUE THREAD

**Issue by 1k2k** [withspectrum/spectrum#3652]
Technical Discussion.

Hi am deploying spectrum on my own domain on AWS, for some reasons i couldn't use NOW.

Your documentations only covers about NOW deployments, so i thought i'd bring up AWS maybe someone in the future might need to do the same.

Please correct me where am wrong.

1. So workers don't need to be discoverable, right? meaning they are bond by redis and i don't need a static url pointing to each.

2. Do I deploy the API server to something like `api.cool-domain.com` for the api?

3. I deploy Hyperion to the root domain, `cool-domain.com`.

4. Where do i forward the rules.json?  Should i set up some proxy on my Hyperion server that proxies the paths in the `rules.json` to my API server, i am correct?

**Comment by mxstbr** [comment]
1. That's right, the only reason we set them at URLs is because they expose a nifty healthcheck server we use to monitor them
2. Yes, but you'll have to forward `cool-domain.com/api` and `cool-domain.com/auth` to `api.cool-domain.com`—we use now path rules for that
3. We deploy it to `hyperion.workers.spectrum.chat` and then tell now to forward `spectrum.chat/**` except for the two paths above
4. Now allows you to do this out of the box!
