### ISSUE TITLE
Top Threads

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#3718]
**Plan**

We want to show the "top conversations" in some thread feeds on landing pages (community view, channel view), instead of just ordering them by last active, to make sure (new) users can jump right into active, engaged conversations. Potentially, we could also be able to use this to show a list of top conversations across the entire platform.

The simplest solution to that is [frecency](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Places/Frecency_algorithm) (frequency + recency), an algorithmic idea from Mozilla. (they use frecency to sort the URL bar suggestions) Instead of just ordering by recency, in our case threadLastActive, you also take the frequency of activity into consideration.

We want to end up with a single number that we can order threads by, the "frecency score". There are a couple notes this algorithm will need to hit:

1. The more activity there is the higher a thread is ranked
2. New threads bubble up quickly if they get activity
3. Old threads can re-bubble up if they get a lot of activity

For threads, there are four properties that together can accomplish these:

- Thread age (for 2.)
- Last active age (for 3.)
- Message count (for 1.)
- Reaction count (for 1.)

All of these need to be weighted, (1 like ≠ 1 message in terms of importance) which means we end up with a calculation that looks like this:

```JS
(messageCount * messageCountWeight)
  + (reactionCount * reactionCountWeight)
  - (threadAgeInDays * threadAgeWeight)
  - (lastActiveInDays * lastActiveWeight)
```

In terms of the weighting, this is a first idea I came up with:

- Message weight: 1
- Reaction weight: 0.2 (i.e. 5 likes = 1 message)
- Thread age weight: 0.25 (i.e. 4 days old = 1 message)
- Last active weight: 0.5 (i.e. 2 days ago = 1 message)

This is obviously just a starting point I made up in my head, I have no clue if that'll give us nice results. I based it on the thoughts that messages are the most important, last active age is more important than thread age and that reactions are the least important. This is very much tbd depending on what gives us nice results.

**Technical notes**

- Since this will be used fairy often, we want an index on the score `r.db('spectrum').table('threads').indexCreate('frecency_score', thread => rank(thread));`
- That means all the properties used in the calculations need to be stored in the `threads` table
- That means we have to denormalize message and reaction counts
- Calculating age in days: `r.round(r.now().sub(thread('createdAt')).div(86400))` (86400 seconds in a day, r.now().sub() gives epoch time)

**Open Questions**

- How do we test this algorithm for nice results?
- How could we incorporate the quality of conversation in the calculation? (maybe unique number of participants?)
- Should we time-bucket somehow, or is thread last active enough? (i.e. a message posted 14 days ago only counts for 50% of a message posted yesterday, a message posted 90 days ago only counts for 10% of a message posted yesterday)

**Comment by brianlovin** [comment]
> How do we test this algorithm for nice results?

Not sure, except to see how things feel in prod and iterate. I think your notes overall are sound, and we may need to just adjust some of the scoring and weighting over time as we get a better feel for what it takes to get a conversation to be "popular"

> How could we incorporate the quality of conversation in the calculation?

Only extra thing I could think of off the top of my head is incorporating message reactions into the mix somehow. E.g a conversation may only have a few messages, but if one of those messages is blowing up with positive reactions maybe it marks a quality conversation (e.g. a question with an answer). That would be quite a lot to denormalize though, so maybe not worth it?

> Should we time-bucket somehow, or is thread last active enough?

I'm in favor of keeping this simple and iterating. Bucketing sounds like it adds quite a lot of implementation detail when it might not matter if the other score weighting takes care of ranking for us.

Curious about a couple more things:
1. How do you envision the index itself working? E.g. are we constantly updating a thread record with a `frecency` key? Or are we only denormalizing the thread like count and message counts and then computing a frecency within the query itself?
2. How should locked threads behave? Immediately drop out of ranking? Or remain wherever they are and degrade with the last active weighting?
3. Would there be any way to approach this with a consideration of the user's participation in a given community? This might be too much for us to work through at the moment, but perhaps there's a weighting given to each user's feed based on how long they have been a member of the community, their role in the community, how often they engage with threads in that community etc. No idea how to approach this at the moment :P 

Otherwise, this looks and sounds great to get us started.

**Comment by mxstbr** [comment]
1. I think if we create a function index (`r.db('spectrum').table('threads').indexCreate('frecency_score', thread => rank(thread));`) it gets recomputed on every query? I'm not sure though, will investigate!
2. Probably not, just degrade—locked threads aren't just used for "closed" conversations, but also for announcements and whatever. It'd be weird to just drop them outright!
3. Yeah we should eventually do this, but it seems more complex atm. E.g. a post by a moderator/an owner should get higher prio than that of a new user—future!

**Comment by brianlovin** [comment]
> I'm not sure though, will investigate!

Yeah, just not sure the mechanics of this. Eager to see what you find out.

Everything else sounds good!
