### ISSUE TITLE
Thread message counting

### ISSUE THREAD

**Issue by littleStudent** [withspectrum/spectrum#3787]
Currently the calculation for the message count is based on the actual message count. This looks like the following:

<img width="1415" alt="screenshot 2018-08-17 16 10 17" src="https://user-images.githubusercontent.com/815520/44270531-117be280-a238-11e8-86d1-d70289e9f3b3.png">

So while it is technically correct that the message count shows `3` it is a bit weird. The 3 messages in there look like a single one but they are actually 3.

It could make sense to group messages together when counting. So multiple messages from a single user would appear as 1. 
But maybe this is not a good idea at all ;). The count simply felt off to me multiple times now because of this behaviour.

If you feel like this behaviour is already correct, plz close the issue!

**Comment by brianlovin** [comment]
Yeah, thanks for the thought - I'm not sure exactly how to address this though, especially from a technical standpoint. I'd say this is lower priority for us, since message count is just a loose proxy to represent "there is stuff happening in this thread" - accuracy actually might not be that important there
