### ISSUE TITLE
Don't show "join communities" onboarding if singing up from a specific community

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#4330]
1. Go to a community as a new user
2. Click "Sign up to join the community"
3. Sign up
4. Get prompted for username
5. Get prompted to join other communities (?!?!?!?!)

It's even worse for private communities as you have the invite link but then get prompted to join other communities with no way out and no way to get back to the private community. Gotta clean that up!

**Comment by brianlovin** [comment]
This behavior broke at some point, it worked this way before. Thanks for filing an issue

**Comment by ahmadawais** [comment]
I just tried and this issue has not been resolved.

1. Went to a private community `https://spectrum.chat/name`
2. Signed up via Twitter
3. Now I am forced to signup at other communities or create one. No way to even skip it or join the community I wanted to join `https://spectrum.chat/name`
4. Since `name` is a private community I can't search it
5. Lost :(

That's why I can't use Spectrum to host a private community like I can on Slack.

Also, I can't share the invite link `https://spectrum.chat/name/join/XXX` since that can get shared anywhere and my community is only for paid users.

I think I set somewhere that members should be approved but the invite link overrides that setting.

Help 👍

**Comment by mxstbr** [comment]
@ahmadawais this hasn't been deployed to production yet, which is why it still doesn't work :blush: We'll let you know when it's live!

**Comment by ahmadawais** [comment]
Sorry. I thought that the merge meant a continuous deployment. Pulling an all-nighter and working too much with Netlify can do that to a person. 

Is there a way for me to subscribe to when this is deployed to production. Or a version number I can track?

**Comment by mxstbr** [comment]
Whatever the next version number will be hah! @brianlovin or myself will ping you once it's out 👍

**Comment by mxstbr** [comment]
This is live now!

**Comment by brianlovin** [comment]
Not yet! Running into some upstream issues at deploy time, but it will be live today

**Comment by mxstbr** [comment]
Oh sorry, listen to @brianlovin
