### ISSUE TITLE
Persist community selection in inbox

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#4618]
Customer feedback: “something that’d be really useful for me is having the ability to pin to a certain community. Eg every time I open spectrum currently I end up on the “everything” tab, which is really not useful to me as I generally only care about one community, so I’m always doing 2 clicks. Basically I’m asking for a feature similar to slack, where it just keeps your open workspace always open until you switch”

**Comment by brianlovin** [comment]
This would be super helpful as well with deleting threads. Since we don't have good cache purging with Apollo, when a user deletes a thread the page gets reloaded. This resets the whole inbox state, which makes it really frustrating to get back to where you were.

So overall: this is a big 💯 from my side, let's do it!
