### ISSUE TITLE
Default Images

### ISSUE THREAD

**Issue by entrptaher** [withspectrum/spectrum#4654]
We cannot access the default image, it's nowhere in the repo. 

Accessing the list [here](https://github.com/withspectrum/spectrum/issues/2862#issuecomment-381802929) yields "URI signature match failed" due to imgix policy, same with S3 saying "Access Denied". 

We do not know the default sizes, cannot replicate them, cannot access them directly or indirectly. But it's needed to make the cards.

What can we do to get/make the images?

**Comment by brianlovin** [comment]
@entrptaher can you tell me more about what you need these for? What cards are you making?

**Comment by entrptaher** [comment]
I need these for this thread called [Status of Self Hosting Spectrum](https://spectrum.chat/spectrum/general/status-of-self-hosting-spectrum~114cbbab-0b0c-4532-b0fd-ab7e830eeab0).

I am not sure why this is restricted.

**Comment by brianlovin** [comment]
@entrptaher of course you can have them, they are unrestricted. I was simply asking so I knew the context in order to send over the right data :)

Here's a dropbox link to a zip with everything you'll need: https://www.dropbox.com/s/7a6h1l0m3004e6z/spectrum_default_images.zip?dl=0

(For future readers, if that link doesn't work for you just reply here and @ mention me please)

**Comment by entrptaher** [comment]
Wow the PNG files are 30-100 times bigger than SVG files :D 
Thanks, I will close this issue for now.

**Comment by SAPikachu** [comment]
@brianlovin The link above no longer works, can you post a new one? We need the assets for our custom Spectrum install, thank you very much!

**Comment by entrptaher** [comment]
We stored a copy on our fork https://github.com/vanila-io/spectrum/tree/alpha/deployment/s3-default-images

**Comment by SAPikachu** [comment]
Oh great, thank you!
