### ISSUE TITLE
Post new threads to the watercooler automatically

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#4670]
As a first step towards a better watercooler experience we should auto-post new threads to it.

**Comment by brianlovin** [comment]
This is going to be a really interesting data design problem, would love to brainstorm here! Specifically, it seems interesting because this will be the first time the system is generating messages on behalf of external actions taking place in the system. Maybe we should loosely try to anticipate other possible actions and make sure that we have a flexible enough system so that our backend can accurately process and the frontend can accurately render different kinds. However, I also recognize how quickly this scope could explode, especially if we consider that certain system messages should probably only be visible to certain users....lol

Here are some quick ideas:
- user posted new thread
- new channel created
- {aggregated by timeframe} users joined community

If we could ever figure out how to have individual messages with viewing permissions, you could have:
- user requested to join community
- user reports
- thread reports

**Comment by mxstbr** [comment]
I think for this v1, I would rather keep the scope tiny and simply post a message with the authors ID and the thread URL as the content. Together with #4669 that should be quick and simple and get us pretty far of the way to the activity feed experience we want and validate that we can make "threads in chat" work!

**Comment by brianlovin** [comment]
Fair enough 👍
