### ISSUE TITLE
Weird image failed rendering in thread body

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4812]
Thread: https://spectrum.chat/abstract/announcements/public-share-links-early-access~d97ae49a-927b-494a-b972-39552a07cc37

What happens:
<img width="716" alt="screenshot 2019-03-04 13 59 30" src="https://user-images.githubusercontent.com/1923260/53755934-d2d11100-3e85-11e9-8f80-88f1ed3e86c2.png">

**Comment by aszx87410** [comment]
Hi, I think it's something to do with [margin collapsing](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing).

When there is an error when rendering image, that's say image not found, the img's height will become 0 and therefore margin doesn't work. So you will see the screenshot below:

<img width="1306" alt="螢幕快照 2019-03-21 上午11 17 58" src="https://user-images.githubusercontent.com/2755720/54731835-73843800-4bcb-11e9-9af5-7bcf17c57a69.png">

There is a simple solution came to my mind, add `alt` attribute should solve the problem. Because if there is any error when rendering image, alt text will appear so that img still get height. Like the screenshot below:

<img width="1324" alt="螢幕快照 2019-03-21 上午11 17 40" src="https://user-images.githubusercontent.com/2755720/54731930-f1e0da00-4bcb-11e9-890e-dcf17a6fb1f6.png">

For alt attribute, it can be something like `error`, `Image not found` or just put the image url as alt. What do you think? @brandly @mxstbr 

I can submit a PR for it, happy to contribute to spectrum 😄

**Comment by brianlovin** [comment]
@aszx87410 this is brilliant - ideally we never break an image, but if one does fail this seems like a more graceful regression than what we currently have. Let's go for it!

**Comment by aszx87410** [comment]
@brianlovin I found that we already render `alt` attribute for image: https://github.com/withspectrum/spectrum/blob/c34bb1fa4b9957bcfcc6ff0165582e2f635bf5e7/shared/clients/draft-js/thread/renderer.js#L164

So it's like an edge case, author embed images without providing alt text. The normal image is like this `![img.png](img_url)` and this one causes the issue: `![](img_url)` because there is no text. 

I think we can just add a default value in case there is no alt text, like `alt={data.alt || 'Image'}`, is it okay? I will submit a PR if it's fine.

**Comment by aszx87410** [comment]
PR created, let me know if there is any issues, thanks. https://github.com/withspectrum/spectrum/pull/4887
