### ISSUE TITLE
Comment count wrong

### ISSUE THREAD

**Issue by schickling** [withspectrum/spectrum#4883]
Here the comment count says `2` but it's actually `1`

![image](https://user-images.githubusercontent.com/1567498/54673183-081e6580-4afa-11e9-9f03-bd61a2832c74.png)

[Actual post](https://spectrum.chat/prisma/general/graphql-and-golang~4843e419-a0f4-462a-baf8-fe4c823415de):

![image](https://user-images.githubusercontent.com/1567498/54673210-18cedb80-4afa-11e9-9772-bc6d27aa896b.png)

**Comment by brianlovin** [comment]
Hm, it looks like it is two discrete comments:

https://spectrum.chat/prisma/general/graphql-and-golang~4843e419-a0f4-462a-baf8-fe4c823415de?m=MTU1MzA3MjE3MjY0MQ==

and

https://spectrum.chat/prisma/general/graphql-and-golang~4843e419-a0f4-462a-baf8-fe4c823415de?m=MTU1MzA3MjI4NzQ5Nw==

I think it's most confusing because it's sent by the same person.
